export const references = {
 whatsapp:{label:'WhatsApp · Pedidos con carrito',url:'https://faq.whatsapp.com/5495780857144067/?cms_platform=iphone&locale=es_LA',type:'Documentación del servicio',scope:'El carrito permite enviar productos del catálogo en un pedido; no equivale a resolver condiciones comerciales.'},
 analytics:{label:'Google Analytics · Embudo de formularios',url:'https://support.google.com/analytics/answer/12944921?hl=es-419',type:'Guía de medición',scope:'Observar pasos del formulario y formular hipótesis sobre abandonos.'},
 blueprint:{label:'Nielsen Norman Group · Service blueprints',url:'https://www.nngroup.com/articles/service-blueprints-definition/',type:'Marco de diseño',scope:'Relacionar la experiencia del cliente con los procesos que la sostienen.'},
 usability:{label:'Nielsen Norman Group · Pruebas de usabilidad',url:'https://www.nngroup.com/articles/usability-testing-101/',type:'Método de investigación',scope:'Observar a participantes realizando tareas para investigar dificultades.'},
 heuristics:{label:'Nielsen Norman Group · Heurísticas',url:'https://www.nngroup.com/articles/ten-usability-heuristics/',type:'Principios de diseño',scope:'Visibilidad del estado, prevención de errores y reconocimiento de opciones.'},
 checking:{label:'Nielsen Norman Group · Verificación de respuestas de IA',url:'https://www.nngroup.com/articles/ai-chatbots-discourage-error-checking/',type:'Análisis de UX',scope:'Dificultades que introduce la interfaz al comprobar contenido generado.'},
 nist:{label:'NIST · Perfil de IA generativa',url:'https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.600-1.pdf',type:'Marco de gestión de riesgos',scope:'Riesgos de contenido falso y necesidad de evaluar el sistema en contexto.'},
 metrics:{label:'GOV.UK · Definir métricas de un servicio',url:'https://www.gov.uk/service-manual/measuring-success/how-to-set-performance-metrics-for-your-service',type:'Guía metodológica',scope:'Vincular hipótesis, datos e indicadores con el propósito del servicio.'},
 journey:{label:'GOV.UK · Medir el recorrido completo',url:'https://www.gov.uk/service-manual/measuring-success/measuring-the-success-of-your-service',type:'Guía metodológica',scope:'Combinar medición e investigación según la transacción o recorrido evaluado.'},
 discovery:{label:'GOV.UK · Fase de descubrimiento',url:'https://www.gov.uk/service-manual/agile-delivery/how-the-discovery-phase-works',type:'Guía metodológica',scope:'Investigar problema, usuarios, restricciones y conveniencia antes de construir.'},
 prices:{label:'Odoo · Listas de precios',url:'https://www.odoo.com/documentation/19.0/applications/sales/sales/products_prices/prices/pricing.html',type:'Documentación de producto',scope:'Reglas por cliente, producto, cantidad y vigencia. No es evidencia de ahorro.'},
 crm:{label:'Odoo · Actividades comerciales',url:'https://www.odoo.com/documentation/19.0/applications/sales/crm/optimize/utilize_activities.html',type:'Documentación de producto',scope:'Organización de actividades y próximos pasos en el seguimiento comercial.'},
 invoice:{label:'Microsoft · Procesamiento de facturas',url:'https://learn.microsoft.com/en-us/ai-builder/prebuilt-invoice-processing',type:'Documentación de producto',scope:'Extracción de datos y tratamiento de documentos en un producto existente.'},
 schedule:{label:'Microsoft · Asistente de planificación',url:'https://learn.microsoft.com/en-us/dynamics365/field-service/schedule-assistant',type:'Documentación de producto',scope:'Disponibilidad, habilidades y ubicación como condiciones de asignación.'},
 flows:{label:'Microsoft · Identificar procesos críticos',url:'https://learn.microsoft.com/en-us/power-platform/well-architected/reliability/identify-flows',type:'Guía técnica',scope:'Identificar y clasificar recorridos según su importancia y fiabilidad.'},
 support:{label:'QJE · Generative AI at Work, 2025',url:'https://doi.org/10.1093/qje/qjae044',type:'Estudio empírico',scope:'Asistencia a agentes de soporte en una empresa. No generalizar el efecto a otros contextos.'},
 writing:{label:'Science · Noy y Zhang, 2023',url:'https://doi.org/10.1126/science.adh2586',type:'Experimento',scope:'Tareas de escritura profesional. No prueba beneficios en una operación completa.'},
 siemens:{label:'Microsoft · Caso Siemens, 2024',url:'https://www.microsoft.com/en/customers/story/19736-siemens-ag-germany-dynamics-365-field-service',type:'Caso del proveedor',scope:'Piloto de informes de servicio. Distingue implementación descrita y resultados esperados.'}
} as const;
export type Ref = keyof typeof references;
// Cada lista corresponde a una sección. Es un fundamento, no una validación del ejemplo hipotético.
export const sectionReferences:Record<string,Ref[][]>={
'automatizar-pedidos-whatsapp':[['whatsapp','blueprint','heuristics'],['discovery'],['heuristics'],['journey']],
'precios-especiales-pedidos':[['prices'],['prices'],['nist','prices'],['metrics']],
'presupuestos-datos-incompletos':[['discovery'],['heuristics'],['prices','nist'],['journey']],
'seguimiento-presupuestos':[['crm'],['crm'],['crm','checking'],['metrics']],
'ia-atencion-cliente':[['blueprint'],['checking'],['support'],['journey']],
'base-conocimiento-ia':[['discovery'],['nist'],['nist','checking'],['nist','usability']],
'revisar-facturas-ia':[['invoice'],['invoice','heuristics'],['invoice'],['journey']],
'integrar-sistemas-sin-ia':[['blueprint'],['flows'],['flows'],['nist','flows']],
'informes-visitas-tecnicas':[['siemens'],['usability'],['siemens'],['journey','checking']],
'coordinar-turnos-reprogramaciones':[['schedule'],['schedule','heuristics'],['schedule'],['metrics']],
'control-calidad-ia':[['nist'],['usability'],['heuristics','checking'],['metrics']],
'analizar-resultados-ia':[['metrics'],['metrics'],['nist'],['journey']],
'adaptar-contenido-ia':[['checking'],['checking','heuristics'],['writing'],['metrics']],
'versiones-catalogo':[['blueprint'],['flows'],['flows'],['journey']],
'chatbot-o-mejorar-ux':[['usability'],['heuristics','usability'],['checking'],['usability']],
'usuarios-abandonan-producto':[['analytics'],['analytics','usability'],['heuristics'],['metrics']],
'elegir-primera-automatizacion':[['discovery'],['flows'],['blueprint'],['metrics']],
'medir-automatizacion':[['journey'],['metrics'],['discovery'],['metrics']],
'piloto-ia-casos-reales':[['nist'],['nist'],['nist'],['discovery']],
'revisar-respuestas-ia':[['checking'],['checking'],['heuristics'],['usability']],
'conocimiento-personas':[['blueprint'],['heuristics'],['checking'],['journey']],
'cuanto-cuesta-automatizar-procesos':[['discovery'],['discovery'],['discovery','metrics'],['journey']],
'auditoria-ux-que-incluye':[['discovery'],['usability'],['heuristics'],['usability']],
'chatgpt-no-alcanza-empresa':[['blueprint'],['blueprint'],['checking'],['journey']]
};
export const searchIntent:Record<string,{query:string;alternatives:string[];reader:string}>={
'automatizar-pedidos-whatsapp':{query:'cómo organizar pedidos de WhatsApp',alternatives:['pasar pedidos de WhatsApp a Excel','automatizar pedidos WhatsApp'],reader:'Responsable de ventas o dueño de distribuidora'},
'precios-especiales-pedidos':{query:'cómo manejar listas de precios por cliente',alternatives:['precios especiales clientes','errores al cotizar pedidos'],reader:'Responsable comercial'},
'presupuestos-datos-incompletos':{query:'cómo hacer presupuestos más rápido',alternatives:['automatizar presupuestos','datos para cotizar uniformes'],reader:'Dueño de un negocio que cotiza a medida'},
'seguimiento-presupuestos':{query:'cómo hacer seguimiento de presupuestos enviados',alternatives:['clientes no responden presupuesto','automatizar seguimiento comercial'],reader:'Responsable de ventas'},
'ia-atencion-cliente':{query:'IA para responder consultas de clientes',alternatives:['automatizar atención al cliente','responder preguntas frecuentes'],reader:'Responsable de atención'},
'base-conocimiento-ia':{query:'chatbot con documentos de mi empresa',alternatives:['base de conocimiento para IA','chatbot respuestas incorrectas'],reader:'Responsable de operaciones'},
'revisar-facturas-ia':{query:'automatizar carga de facturas',alternatives:['extraer datos de facturas PDF','IA para revisar facturas'],reader:'Responsable administrativo'},
'integrar-sistemas-sin-ia':{query:'cómo dejar de copiar datos entre sistemas',alternatives:['integrar planillas y CRM','automatizar carga de datos'],reader:'Responsable de operaciones'},
'informes-visitas-tecnicas':{query:'automatizar informes de visitas técnicas',alternatives:['hacer reportes desde notas','IA informes mantenimiento'],reader:'Empresa de mantenimiento'},
'coordinar-turnos-reprogramaciones':{query:'automatizar agenda de turnos',alternatives:['coordinar visitas técnicas','gestionar reprogramaciones'],reader:'Coordinador de operaciones'},
'control-calidad-ia':{query:'IA para revisar documentos y detectar errores',alternatives:['automatizar control de calidad documentos','revisión de entregas'],reader:'Responsable de calidad'},
'analizar-resultados-ia':{query:'cómo analizar reportes con inteligencia artificial',alternatives:['reportes con datos diferentes','IA para indicadores de negocio'],reader:'Gerente o dueño'},
'adaptar-contenido-ia':{query:'IA para descripciones de productos',alternatives:['adaptar textos para redes','generar fichas de productos'],reader:'Responsable de marketing'},
'versiones-catalogo':{query:'cómo mantener actualizado el catálogo de productos',alternatives:['sincronizar precios en varios canales','actualizar fichas productos'],reader:'Responsable de comercio o marketing'},
'chatbot-o-mejorar-ux':{query:'mis clientes no entienden cómo usar mi app',alternatives:['mejorar experiencia de usuario','chatbot para ayudar usuarios'],reader:'Fundador o responsable de producto'},
'usuarios-abandonan-producto':{query:'por qué los usuarios abandonan mi aplicación',alternatives:['usuarios no completan registro','mejorar conversión formulario'],reader:'Responsable de producto'},
'elegir-primera-automatizacion':{query:'qué procesos puedo automatizar en mi empresa',alternatives:['automatización para pymes por dónde empezar','IA para mi negocio'],reader:'Dueño de pyme'},
'medir-automatizacion':{query:'cómo medir el ahorro de una automatización',alternatives:['ROI automatización procesos','cómo saber si la IA ahorra tiempo'],reader:'Dueño o gerente'},
'piloto-ia-casos-reales':{query:'mi automatización con IA falla',alternatives:['piloto IA no funciona','IA errores casos reales'],reader:'Responsable de una prueba de IA'},
'revisar-respuestas-ia':{query:'cómo verificar respuestas de inteligencia artificial',alternatives:['controlar errores de IA','revisión humana IA'],reader:'Responsable de producto u operaciones'},
'conocimiento-personas':{query:'cómo documentar procesos de una empresa',alternatives:['equipo depende de una persona','organizar conocimiento interno'],reader:'Dueño o líder de equipo'},
'cuanto-cuesta-automatizar-procesos':{query:'cuánto cuesta automatizar procesos en una pyme',alternatives:['precio automatización con IA','presupuesto automatización empresa'],reader:'Comprador comparando proveedores'},
'auditoria-ux-que-incluye':{query:'qué incluye una auditoría UX',alternatives:['contratar auditoría UX','auditoría UX para mi aplicación'],reader:'Comprador de servicios de diseño'},
'chatgpt-no-alcanza-empresa':{query:'cómo integrar ChatGPT en los procesos de mi empresa',alternatives:['usamos ChatGPT pero no ahorramos tiempo','automatización más allá de ChatGPT'],reader:'Dueño o responsable de operaciones'}
};
