export type Detail={label:string; question:string; options:string[]; opportunity:string; check:string};
export type Flow={id:string; group:string; name:string; verb:string; states:string[]; details:Detail[]};
const d=(label:string,question:string,options:string[],opportunity:string,check:string):Detail=>({label,question,options,opportunity,check});
export const levels=['Todavía no la usamos y queremos descubrir dónde puede servir.','Algunas personas la usan por su cuenta para tareas del día a día.','Estamos probándola en un proceso concreto.','Ya la usamos en algunos procesos, pero necesitamos mejorar cómo funciona.','La usamos en varias áreas y medimos sus resultados.','No tengo suficiente información para responder.'];
export const flows:Flow[]=[
{id:'consultas',group:'Clientes y ventas',name:'Responder consultas de clientes',verb:'responden las consultas',states:['Escribimos cada respuesta, incluso cuando la consulta se repite.','Tenemos respuestas guardadas, pero cuesta encontrar la adecuada.','Lo habitual funciona; los casos particulares pasan por varias personas.'],details:[
d('Preguntas que se repiten','¿Dónde está la respuesta que el equipo necesita?',['Está documentada y actualizada.','Está repartida entre documentos y conversaciones.','Depende de lo que recuerda cada persona.'],'Encontrar una respuesta respaldada por información vigente antes de enviarla.','Tomar consultas reales y comprobar si la documentación permite responderlas sin inventar datos.'),
d('Consultas sobre un pedido o una cuenta','¿Cómo obtienen el estado de ese caso?',['El dato está actualizado en un sistema.','Hay que consultar varios sistemas.','Hay que preguntarle a otra persona.'],'Reunir el estado del caso en un solo lugar para preparar una respuesta.','Verificar acceso, permisos y actualización de la información antes de conectar un asistente.'),
d('Derivaciones entre personas','Cuando derivan una consulta, ¿qué recibe la siguiente persona?',['El historial completo y el motivo.','Solo una parte y debe volver a preguntar.','No está claro quién debería recibirla.'],'Conservar el contexto y orientar la consulta hacia quien pueda resolverla.','Revisar derivaciones reales y acordar qué señales identifican cada tipo de consulta.') ]},
{id:'presupuestos',group:'Clientes y ventas',name:'Preparar presupuestos y seguir ventas',verb:'preparan y siguen los presupuestos',states:['Cada presupuesto se arma desde cero.','Reutilizamos una base, pero ajustamos condiciones a mano.','Cotizamos bien; el seguimiento y las excepciones se nos dispersan.'],details:[
d('Faltan datos para cotizar','¿Qué ocurre cuando llega una solicitud incompleta?',['Tenemos una lista clara de lo que falta.','Cada vendedor pide datos diferentes.','Hay que hablar con un especialista para saber qué pedir.'],'Guiar la recolección de los datos necesarios antes de preparar una cotización.','Definir campos mínimos por tipo de venta y comprobar cuáles requieren criterio experto.'),
d('Precios o condiciones particulares','¿Cómo deciden el precio aplicable?',['Hay reglas y acuerdos registrados.','Buscamos acuerdos en mensajes y archivos.','Se negocia desde cero en cada caso.'],'Preparar condiciones respaldadas por acuerdos existentes; conservar la negociación cuando sea necesaria.','Distinguir reglas recuperables de decisiones comerciales nuevas.'),
d('Se pierde el seguimiento','Después de enviar el presupuesto, ¿qué queda registrado?',['Responsable y próxima fecha de contacto.','Solo el mensaje enviado.','El contexto queda en la memoria del vendedor.'],'Organizar próximos pasos y preparar seguimientos con el contexto de cada oportunidad.','Comprobar primero si el sistema comercial ya permite registrar y recordar esas acciones.') ]},
{id:'pedidos',group:'Clientes y ventas',name:'Recibir pedidos y coordinar entregas',verb:'procesan los pedidos',states:['Los cargamos a mano y generalmente quedan completos.','Entran al sistema, pero corregimos productos, cantidades o precios.','Los pedidos habituales funcionan bien; los especiales nos traban.'],details:[
d('Precios acordados con cada cliente','¿Cómo saben qué precio especial corresponde?',['Está registrado y el sistema lo aplica.','Hay que buscar el acuerdo en mensajes o documentos.','Hay que negociarlo de nuevo para cada pedido.'],'Recuperar el acuerdo vigente y mostrar su respaldo antes de confirmar el pedido.','Detectar acuerdos vencidos o contradictorios; no inferir precios sin respaldo.'),
d('Nombres distintos para el mismo producto','¿Cómo identifican lo que el cliente pidió?',['Tenemos equivalencias registradas.','Alguien reconoce el producto por experiencia.','A veces hay que consultar al cliente.'],'Sugerir coincidencias con el catálogo y señalar ambigüedades para revisión.','Probar con pedidos reales y exigir confirmación cuando haya más de una coincidencia posible.'),
d('Falta de stock o cambios en la entrega','¿Qué hace el equipo cuando no puede cumplir el pedido original?',['Aplica alternativas acordadas y disponibles.','Consulta stock y luego negocia una alternativa.','Se entera del problema después de confirmar.'],'Detectar restricciones antes de confirmar y preparar alternativas verificables.','Revisar disponibilidad real y quién autoriza cambios; no prometer stock o entregas sin confirmación.') ]},
{id:'documentos',group:'Operación y administración',name:'Revisar facturas y documentos',verb:'revisan los documentos',states:['Leemos cada documento y copiamos los datos.','Extraemos datos automáticamente, pero corregimos muchos campos.','Los formatos habituales funcionan; los documentos diferentes frenan el proceso.'],details:[
d('Formatos y datos variables','¿Qué cambia entre los documentos?',['Solo cambia la ubicación de campos conocidos.','Cambian los nombres y la forma de expresar los datos.','También cambia qué información es obligatoria.'],'Extraer campos y marcar datos faltantes según el tipo de documento.','Definir ejemplos por formato y medir errores por campo, no solo documentos procesados.'),
d('Diferencias con lo acordado','¿Contra qué verifican importes o cantidades?',['Contra una orden o contrato disponible.','Contra varios archivos y mensajes.','No hay una referencia única.'],'Comparar documentos con su referencia y destacar discrepancias.','Acordar una fuente válida y tolerancias; los cálculos deben verificarse con reglas explícitas.'),
d('Duplicados o versiones distintas','¿Cómo reconocen un documento repetido?',['Usamos identificadores consistentes.','Comparamos nombres, fechas e importes a mano.','Suele descubrirse después de procesarlo.'],'Señalar posibles duplicados antes de procesarlos.','Distinguir duplicados de documentos corregidos; una coincidencia no autoriza descartarlos.') ]},
{id:'sistemas',group:'Operación y administración',name:'Pasar información entre sistemas',verb:'trasladan información entre herramientas',states:['Copiamos los mismos datos en varias herramientas.','Hay una conexión, pero algunos campos no coinciden.','Lo habitual se sincroniza; los cambios y errores quedan pendientes.'],details:[
d('Volver a cargar los mismos datos','¿Los campos significan lo mismo en ambos sistemas?',['Sí, tienen una correspondencia clara.','Hay que transformar formatos o unidades.','Hay que interpretar texto para completarlos.'],'Conectar el traslado de datos; reservar IA para los campos que requieren interpretación.','Comprobar integraciones existentes y una correspondencia de campos verificable.'),
d('Datos contradictorios','Cuando dos sistemas muestran algo distinto, ¿cuál vale?',['Existe una fuente principal definida.','Depende del tipo de dato.','Lo decide alguien cada vez.'],'Definir cómo resolver diferencias antes de automatizar la sincronización.','Acordar autoridad por campo y evitar que una actualización sobrescriba información válida.'),
d('Errores que nadie ve','¿Cómo detectan que una transferencia falló?',['Hay una alerta y una persona asignada.','Se revisan registros manualmente.','Nos enteramos cuando alguien necesita el dato.'],'Hacer visibles las transferencias fallidas y permitir recuperarlas.','Verificar registros, alertas y reintentos sin duplicar operaciones.') ]},
{id:'conocimiento',group:'Información y producto',name:'Buscar información para el equipo',verb:'encuentran respuestas dentro de la empresa',states:['Buscamos en carpetas y conversaciones.','Hay documentación, pero no sabemos qué versión usar.','Lo habitual se encuentra; lo específico depende de ciertas personas.'],details:[
d('Información dispersa','¿Dónde termina apareciendo la respuesta?',['En documentos identificables.','En conversaciones de distintos canales.','En el conocimiento de una persona.'],'Facilitar la búsqueda con fuentes visibles y conservar lo que hoy solo saben algunas personas.','Verificar permisos y qué conocimiento existe realmente antes de ofrecer respuestas automáticas.'),
d('Versiones contradictorias','¿Cómo distinguen una instrucción vigente de una vieja?',['Tiene fecha y responsable de actualización.','Hay varias versiones sin una clara.','Se confirma preguntando a alguien.'],'Identificar la fuente vigente antes de responder consultas internas.','Definir responsables y reglas de vigencia; un buscador no resuelve contradicciones por sí solo.'),
d('Depender de un especialista','¿Qué necesita aportar esa persona?',['Un dato o procedimiento que ya conoce.','Interpretar el contexto del caso.','Tomar una decisión nueva.'],'Separar información reutilizable de decisiones que requieren experiencia.','Documentar casos frecuentes y conservar la consulta experta donde cambian las condiciones.') ]},
{id:'coordinacion',group:'Operación y administración',name:'Coordinar turnos, visitas o tareas',verb:'coordinan turnos y tareas',states:['Coordinamos por mensajes y planillas.','Usamos un calendario, pero ajustamos restricciones a mano.','La agenda funciona; los cambios de último momento son difíciles.'],details:[
d('Encontrar un horario posible','¿Qué hay que hacer coincidir?',['Solo disponibilidad de personas.','Personas, equipos o espacios.','También ubicación, duración o habilidades.'],'Evaluar una agenda que contemple las restricciones reales.','Listar restricciones y verificar si un sistema de reservas ya las cubre; no todo requiere IA.'),
d('Reprogramaciones','Cuando cambia un turno, ¿qué pasa con el resto?',['Se actualiza y avisa automáticamente.','Hay que avisar y modificar varios lugares.','Hay que reorganizar otros turnos.'],'Preparar los cambios y sus consecuencias para revisión.','Comprobar permisos, confirmaciones y cómo evitar notificaciones contradictorias.'),
d('Pedidos poco claros','¿Cómo llega la solicitud de visita o tarea?',['Con datos completos en un formulario.','Por mensajes con información dispersa.','Con audios o descripciones ambiguas.'],'Convertir solicitudes en una ficha y pedir los datos faltantes.','Separar interpretación de confirmación de agenda; nunca reservar basándose en una suposición.') ]},
{id:'informes',group:'Información y producto',name:'Preparar informes',verb:'preparan los informes',states:['Redactamos cada informe desde notas y archivos.','Usamos una plantilla, pero reunir los datos lleva tiempo.','Lo habitual está resuelto; cada cliente pide una versión distinta.'],details:[
d('Notas incompletas','¿Qué suele faltar al preparar el informe?',['Ordenar información que ya está.','Datos que alguien olvidó registrar.','Conclusiones que requieren criterio profesional.'],'Preparar un borrador y destacar vacíos, sin completar hechos que no fueron registrados.','Comparar notas e informes reales y distinguir hechos de interpretación.'),
d('Reunir datos de varios lugares','¿Cómo relacionan la información de un mismo caso?',['Existe un identificador común.','Se cruza por nombres y fechas.','Alguien tiene que reconocer qué corresponde.'],'Reunir evidencia del caso y mantener su origen visible.','Verificar identificadores y coincidencias ambiguas antes de unir registros.'),
d('Adaptar el informe al destinatario','¿Qué cambia según quién lo recibe?',['El formato y el nivel de detalle.','Las secciones o datos que necesita.','Las conclusiones y decisiones a evaluar.'],'Adaptar la presentación de información validada al destinatario.','Definir contenido obligatorio y evitar que una adaptación cambie los hechos o las conclusiones aprobadas.') ]},
{id:'calidad',group:'Operación y administración',name:'Revisar calidad y requisitos',verb:'comprueban que el trabajo esté completo',states:['Cada persona revisa según su experiencia.','Hay una lista, pero se verifica a mano.','Las reglas simples funcionan; los casos ambiguos necesitan revisión.'],details:[
d('Requisitos que se olvidan','¿Cómo están definidos los requisitos?',['Son claros y se pueden comprobar.','Están repartidos en varios documentos.','Dependen del criterio de quien revisa.'],'Preparar una revisión trazable contra requisitos explícitos.','Definir la lista vigente y separar comprobaciones objetivas de juicios expertos.'),
d('Diferencias entre revisores','¿Por qué dos personas llegan a conclusiones distintas?',['Usan versiones distintas de los criterios.','Interpretan diferente el mismo criterio.','Evalúan contextos diferentes.'],'Hacer visibles los criterios y las razones de cada observación.','Calibrar con ejemplos revisados; no presentar una opinión automática como certificación.'),
d('Detectar problemas demasiado tarde','¿Cuándo se encuentra el problema?',['Antes de entregar y se corrige fácilmente.','Al final, cuando corregir es costoso.','Lo encuentra el cliente.'],'Adelantar comprobaciones en puntos concretos del proceso.','Medir falsos avisos y problemas omitidos antes de depender de la revisión automática.') ]},
{id:'analisis',group:'Información y producto',name:'Analizar resultados para decidir',verb:'analizan resultados',states:['Juntamos datos a mano antes de analizarlos.','Tenemos reportes, pero cuesta explicar las diferencias.','Los indicadores están; falta convertirlos en decisiones.'],details:[
d('Números que no coinciden','¿Qué causa las diferencias entre reportes?',['Fechas o filtros distintos.','Definiciones distintas del mismo indicador.','Todavía no lo sabemos.'],'Alinear definiciones y fuentes antes de interpretar los resultados.','Conciliar una muestra; la IA no debe decidir qué cifra es correcta sin una referencia.'),
d('Encontrar cambios relevantes','¿Cómo detectan algo fuera de lo habitual?',['Con umbrales definidos.','Alguien revisa gráficos y lo reconoce.','Cuando ya tuvo consecuencias.'],'Señalar variaciones y reunir contexto para investigarlas.','Definir una referencia, estacionalidad y costo de falsas alertas; no confundir correlación con causa.'),
d('Decidir qué hacer','¿Qué falta después de ver un indicador?',['Encontrar los datos que explican el cambio.','Comparar alternativas de acción.','Acordar una decisión entre responsables.'],'Preparar evidencia y alternativas para una decisión informada.','Separar hechos, hipótesis y decisiones; comprobar resultados después de actuar.') ]},
{id:'contenido',group:'Clientes y ventas',name:'Actualizar catálogos y materiales',verb:'crean y actualizan materiales',states:['Reescribimos información para cada canal.','Generamos borradores, pero corregirlos lleva mucho tiempo.','Publicamos bien; mantener todo actualizado es lo difícil.'],details:[
d('Adaptar información a cada canal','¿Qué cambia entre versiones?',['El largo y el formato.','El público y los argumentos.','También las condiciones comerciales.'],'Preparar variantes a partir de información aprobada.','Separar cambios de estilo de cambios de hechos, precios o promesas.'),
d('Errores en los borradores','¿Qué es lo que más corrigen?',['Tono y estilo.','Datos de productos o servicios.','Afirmaciones que no podemos respaldar.'],'Guiar la redacción con fuentes y criterios de revisión.','Evaluar ejemplos reales; los datos y afirmaciones necesitan respaldo antes de publicar.'),
d('Versiones desactualizadas','Cuando cambia un producto, ¿cómo actualizan los materiales?',['Hay una fuente que actualiza todos los canales.','Se modifica cada canal por separado.','No sabemos dónde sigue la versión anterior.'],'Rastrear dónde se usa la información y preparar actualizaciones.','Inventariar canales y aprobación; comprobar si una integración ya resuelve el problema.') ]},
{id:'producto',group:'Información y producto',name:'Ayudar a usar nuestro producto',verb:'ayudan a las personas a usar el producto',states:['Explicamos personalmente cómo empezar.','Hay tutoriales, pero recibimos las mismas dudas.','El inicio funciona; ciertos pasos necesitan ayuda.'],details:[
d('No se entiende qué hacer','¿Dónde se traban las personas?',['En un paso que podemos identificar.','En distintos lugares según su objetivo.','Todavía no lo observamos directamente.'],'Observar el recorrido y mejorar la orientación en el punto de dificultad.','Probar con usuarios reales; no asumir que un chatbot es mejor que una pantalla más clara.'),
d('Dudas sobre su caso particular','¿Qué necesitan saber para avanzar?',['Una instrucción general.','Una respuesta que depende de sus datos.','Una recomendación que requiere criterio experto.'],'Evaluar ayuda contextual según la tarea y la información disponible.','Verificar permisos, contexto y límites; mantener intervención experta cuando corresponda.'),
d('Abandonan antes de terminar','¿Qué evidencia tienen del abandono?',['Sabemos en qué paso ocurre.','Tenemos comentarios, pero no datos del recorrido.','Solo sabemos que no vuelven.'],'Relacionar señales de uso con investigación para elegir una mejora.','Distinguir problemas de comprensión, valor y funcionamiento antes de construir otra función.') ]}
];
export const statesTail=['Funciona bien, incluso cuando aparecen casos diferentes.','No tengo suficiente información.'];
export const evidenceOptions=['Hay una fuente identificada y actualizada.','La información existe, pero está repartida.','Depende de lo que sabe una persona.','Cambia en cada caso; no hay una respuesta fija.','No lo sé.'];
export const impactOptions=['Se acumula trabajo o alguien queda esperando.','Aparecen errores y hay que repetir trabajo.','Nos limita para atender más pedidos o clientes.','Funciona bien y lleva poco esfuerzo.','Todavía no lo medimos.'];
export const frequencyOptions=['Varias veces por día.','Algunas veces por semana.','Ocasionalmente.','No lo sé.'];
export const controlOptions=['Siempre debe revisarlo una persona antes de avanzar.','Se pueden resolver los casos habituales y revisar las excepciones.','Todavía no tenemos claro dónde debería estar la revisión.'];
export type Answers={state?:number;issue?:number;detail?:number;impact?:number;frequency?:number;control?:number};
export function outcome(f:Flow,a:Answers){const x=f.details[a.issue??0]??{label:"Situación por explorar",opportunity:"Entender la situación antes de recomendar una herramienta.",check:"Identificar un caso concreto de esta actividad y qué sucede hoy."};if(a.state===3||a.impact===3)return {kind:'Sin prioridad de cambio',title:'Conservar lo que funciona',body:'Tus respuestas no muestran una dificultad que justifique sumar una herramienta ahora.',next:'Revisar si cambia el volumen, el esfuerzo o la calidad antes de invertir.',check:'Esta conclusión solo cubre la actividad explorada.'};if(a.state===4||a.issue===f.details.length||a.detail===3||a.impact===4||a.frequency===3)return {kind:'Falta evidencia',title:'Entender mejor antes de elegir una solución',body:'Hay aspectos de esta actividad que todavía no pudimos confirmar. Una recomendación de automatización sería prematura.',next:'Registrar algunos casos reales, el tiempo que llevan y dónde requieren intervención.',check:x.check};if(a.frequency===2)return {kind:'Evaluar conveniencia',title:'Una mejora posible, todavía sin justificar la inversión',body:x.opportunity,next:'Por su frecuencia ocasional, comparar primero el esfuerzo actual con el costo de implementar y mantener una solución.',check:x.check};return {kind:'Oportunidad para investigar',title:x.label,body:x.opportunity,next:(a.state===1?'Revisar primero qué falla en las herramientas que ya usan. ':'')+'Probar con una muestra de casos reales y comparar tiempo, errores y necesidad de revisión.',check:x.check};}
