import {outcome as previous,type Flow,type Answers} from './flows';
// One actionable check per substantive answer, kept separate from the baseline versions.
export const detailChecks:Record<string,string[][]>={
consultas:[['Comprobar que las respuestas vigentes cubran consultas reales y citar el documento usado.','Reunir las respuestas dispersas y resolver contradicciones antes de automatizar.','Registrar respuestas del equipo y hacerlas revisar antes de ofrecerlas a clientes.'],['Verificar permisos y actualización del dato antes de conectarlo a una respuesta.','Comprobar cómo vincular los registros de cada sistema sin confundir cuentas.','Identificar quién confirma el dato y cómo obtenerlo sin prometer una respuesta inmediata.'],['Comprobar si la demora ocurre después de recibir el historial, antes de cambiar la derivación.','Definir qué contexto debe acompañar cada transferencia para evitar preguntas repetidas.','Acordar destinos y criterios de derivación antes de distribuir consultas.']],
presupuestos:[['Probar una ficha con la lista existente y revisar si evita intercambios adicionales.','Comparar casos de vendedores distintos y acordar los datos necesarios.','Registrar qué evalúa el especialista y qué casos deben seguir llegando a él.'],['Comprobar vigencia y aplicación de las reglas con cotizaciones anteriores.','Localizar acuerdos vigentes y conservar su respaldo antes de sugerir un precio.','Separar la preparación de antecedentes de la negociación que requiere una persona.'],['Revisar si las fechas se cumplen y qué impide contactar antes de sumar recordatorios.','Registrar responsable y próximo contacto junto al mensaje.','Recuperar el contexto de casos recientes con el vendedor antes de generar seguimientos.']],
pedidos:[['Revisar por qué se frena el pedido si el sistema ya aplica el acuerdo.','Probar la búsqueda de acuerdos vigentes, mostrando el documento que respalda cada precio.','Preparar antecedentes para negociar; no aplicar como vigente un precio todavía sin acordar.'],['Comprobar cobertura y actualización de las equivalencias con pedidos reales.','Registrar cómo el equipo reconoce productos y convertir ejemplos revisados en equivalencias.','Identificar qué dato falta y preparar una pregunta al cliente antes de elegir un producto.'],['Comprobar que las alternativas acordadas sigan disponibles al confirmar.','Separar la consulta de stock de la aprobación del cliente para sustituir el producto.','Revisar cómo confirmar disponibilidad antes de comprometer una entrega.']],
documentos:[['Probar extracción de campos conocidos en distintos diseños de documento.','Definir equivalencias de nombres y revisar interpretaciones con documentos reales.','Acordar los requisitos por tipo de documento antes de comprobar campos faltantes.'],['Comparar datos contra la referencia vigente y mostrar cada diferencia.','Reunir las referencias y resolver qué acuerdo prevalece.','Definir una referencia aprobada antes de automatizar comparaciones.'],['Probar detección por identificadores y revisar duplicados legítimos.','Comparar coincidencias aproximadas y exigir revisión antes de descartar documentos.','Ubicar una comprobación previa al procesamiento y medir los duplicados que detecta.']],
sistemas:[['Revisar una integración directa de campos antes de considerar IA.','Documentar conversiones y probar unidades y formatos extremos.','Reunir textos representativos y comprobar qué datos se pueden extraer sin adivinar.'],['Comprobar por qué las copias difieren de la fuente principal.','Definir la fuente válida para cada dato y cómo sincronizarla.','Acordar cómo resolver conflictos antes de propagar datos.'],['Revisar si la alerta llega a tiempo y si permite resolver el error.','Identificar fallos en los registros para convertirlos en alertas útiles.','Definir señales de fallo y avisos antes de que alguien necesite el dato.']],
conocimiento:[['Probar búsqueda con documentos vigentes y mostrar el fragmento de respaldo.','Seleccionar información reutilizable de las conversaciones y validarla.','Documentar casos con la persona que conoce el proceso antes de crear un buscador.'],['Comprobar que la búsqueda priorice la versión vigente.','Resolver versiones contradictorias antes de generar respuestas.','Registrar quién confirma vigencia y cómo queda reflejada esa confirmación.'],['Documentar el procedimiento y probar si otros pueden aplicarlo.','Registrar ejemplos y excepciones que usa el especialista para interpretar el caso.','Preparar antecedentes para el especialista sin delegar automáticamente una decisión nueva.']],
coordinacion:[['Probar disponibilidad compartida y reglas simples de reserva.','Comprobar disponibilidad simultánea de personas, equipos y espacios.','Documentar restricciones de traslado, duración y habilidades antes de asignar turnos.'],['Revisar si los avisos llegan y si el cambio se confirma.','Identificar todos los registros que deben cambiar y verificar su actualización.','Probar el efecto de una reprogramación sobre los demás turnos antes de confirmarla.'],['Comprobar qué impide coordinar aun con los datos completos.','Preparar una ficha desde mensajes y señalar datos faltantes.','Confirmar la interpretación de audios o descripciones antes de asignar la tarea.']],
informes:[['Probar un borrador que ordene las notas sin agregar hechos.','Mejorar el registro durante la tarea: un borrador no recupera datos que nadie anotó.','Separar los hechos registrados de las conclusiones que debe validar el profesional.'],['Verificar cruces por identificador y detectar registros ausentes.','Probar coincidencias por nombre y fecha con revisión de casos ambiguos.','Registrar cómo la persona vincula cada dato antes de automatizar esa asociación.'],['Probar plantillas con distinto formato conservando los mismos hechos.','Definir qué información necesita cada destinatario y comprobar omisiones.','Mantener la revisión profesional de las conclusiones y decisiones sugeridas.']],
calidad:[['Convertir requisitos comprobables en controles y probar fallos conocidos.','Reunir requisitos vigentes y resolver contradicciones antes de revisar automáticamente.','Documentar ejemplos del criterio del revisor y sus límites.'],['Unificar la versión de los criterios antes de automatizar la revisión.','Comparar casos con ambos revisores y aclarar interpretaciones diferentes.','Precisar qué criterios cambian con el contexto y probar esos casos por separado.'],['Medir el esfuerzo actual de corregir antes de justificar otra herramienta.','Probar un control anterior que detecte el mismo defecto antes de que corregir sea costoso.','Reconstruir un defecto reportado por el cliente y ubicar dónde habría podido detectarse.']],
analisis:[['Alinear fechas y filtros y volver a comparar los resultados.','Acordar una definición del indicador antes de reunir cifras.','Rastrear un indicador hasta sus fuentes antes de interpretar la diferencia.'],['Probar si los umbrales detectan cambios útiles sin exceso de avisos.','Registrar qué señales reconoce la persona y probarlas con datos anteriores.','Reconstruir un cambio pasado y comprobar qué señal habría permitido advertirlo.'],['Vincular el cambio a sus datos de origen sin confundir correlación con causa.','Explicitar criterios y comparar alternativas, conservando sus supuestos.','Preparar evidencia para la conversación entre responsables, sin presentar una decisión automática.']],
contenido:[['Probar adaptaciones de formato conservando datos y significado.','Revisar argumentos y lenguaje con ejemplos del público al que se dirigen.','Comprobar condiciones vigentes por canal antes de publicar una adaptación.'],['Definir ejemplos del tono y comprobar si disminuyen las correcciones.','Conectar los borradores con información vigente y verificar cada dato.','Identificar afirmaciones sin respaldo y retirarlas o documentarlas antes de publicar.'],['Comprobar por qué una actualización no llega a todos los destinos.','Enumerar canales y verificar la actualización de cada uno.','Localizar las versiones publicadas antes de automatizar cambios.']],
producto:[['Observar ese paso con usuarios y comprobar qué información o acción les falta.','Separar recorridos por objetivo y observar dónde se pierde cada grupo.','Observar intentos reales antes de atribuir el problema a una pantalla.'],['Probar si una instrucción visible en el momento adecuado resuelve la duda.','Verificar qué datos del usuario hacen falta y cómo obtenerlos con permiso.','Definir cuándo derivar a un experto y qué antecedentes preparar.'],['Investigar ese paso y contrastar datos de abandono con observación.','Relacionar comentarios con etapas del recorrido antes de elegir una mejora.','Medir el recorrido y distinguir abandono de finalización antes de rediseñar.']]
};
export function outcome(f:Flow,a:Answers){
 const base=previous(f,a);
 if(base.kind==='Sin prioridad de cambio')return base;
 if(base.kind==='Falta evidencia')return {...base,check:'Confirmar el dato que quedó sin responder con un caso real de esta actividad.'};
 const check=detailChecks[f.id]?.[a.issue??-1]?.[a.detail??-1];
 if(!check)return base;
 const unknown=(f.id==='analisis'&&a.issue===0&&a.detail===2)||(f.id==='producto'&&a.issue===0&&a.detail===2);
 if(unknown)return {...base,kind:'Falta evidencia',title:'Entender mejor antes de elegir una solución',body:'Todavía falta observar qué ocurre en este punto para recomendar un cambio.',check,next:'Reunir esa evidencia y volver a evaluar el caso.'};
 return {...base,check,next:(a.state===1?'Revisar primero la herramienta que ya usan. ':'')+(base.kind==='Evaluar conveniencia'?'Comparar el esfuerzo ocasional con el costo de implementar y mantener el cambio.':'Probar el cambio con casos reales y comparar tiempo, errores e intervención necesaria con la forma actual de trabajar.')};
}
